export const sample = "The teacher gave the students a useful book yesterday.";
const examples = [
  { title: "双宾语 · 过去时", text: sample },
  { title: "双宾语 · 现在时", text: "She gives him a new book today." },
  { title: "双宾语 · 更换动词", text: "They sent the children small gifts." },
  { title: "主谓", text: "The children smiled yesterday." },
  { title: "主谓宾", text: "She likes the useful book." },
  { title: "主系表", text: "The book is useful." },
  { title: "宾语补足语", text: "We found the book useful." },
  { title: "一般疑问句", text: "Did she give him a book yesterday?" },
  { title: "祈使句", text: "Be kind." },
  { title: "感叹句", text: "What a useful book it is!" },
  { title: "基础纠错", text: "She go to school." },
  { title: "情态动词", text: "She can go to school." },
  { title: "否定陈述", text: "She does not like the book." },
  { title: "否定表语", text: "The book is not useful." },
  { title: "can 否定", text: "She can not go to school." },
  { title: "can 疑问", text: "Can she give him a book?" },
  { title: "冠词短语", text: "It is an old book." },
  { title: "宾语代词", text: "We found it useful." },
  { title: "否定句纠错", text: "She do not likes books." },
  { title: "条件 · if", text: "If she sleeps, he smiles." },
  { title: "条件 · 分句定语", text: "If the young teacher gives her an old book, the book is useful." },
  { title: "原因 · because", text: "She smiles because she likes the book." },
  { title: "原因 · 分句定语", text: "The young teacher gives her an old book because the book is useful." },
  { title: "并列 · and", text: "She sleeps and he smiles." },
  { title: "并列 · but", text: "She likes the book, but he likes the toy." },
  { title: "并列 · 不同句型", text: "She is kind and we found it useful." },
  { title: "范围提示", text: "The weather is beautiful today." },
];
export const exampleGroups = [
  { title: "新增常用词汇", scope: "44 组可数名词、24 个形容词、26 个动词词元；按限定搭配分析。read 同形句可能无法唯一确定时态。", examples: [{ title: "人物接受者", text: "The doctor teaches the children a useful book." }, { title: "不规则复数", text: "The women carry the apples." }, { title: "新词完成时", text: "The nurse has written a letter." }, { title: "新词宾补", text: "She keeps the door clean." }, { title: "同形歧义", text: "They read books." }] },
  { title: "常用谓语组合", scope: "完成进行、完成被动、进行被动；不支持完成进行被动或新的 can 组合。", examples: [{ title: "完成进行", text: "She has been sleeping." }, { title: "完成被动", text: "A book has been given to her." }, { title: "进行被动", text: "She is being given a book." }] },
  { title: "被动语态", scope: "限定 SVO/SVOO 被动转换；接受者与施事分别用 to/by 说明，句型按表层成分标注。", examples: [{ title: "被动 · 宾语提升", text: "The book was liked by her." }, { title: "被动 · 接受者提升", text: "She is given a book." }, { title: "被动 · 直接宾语提升", text: "A book is given to her." }] },
  { title: "完成时", scope: "现在/过去完成时，含 been + 表语；助动词承担人称，实义动词使用过去分词。", examples: [{ title: "完成 · 不规则分词", text: "She has given him a book." }, { title: "完成 · 系表", text: "They had been kind." }] },
  { title: "进行时", scope: "现在/过去进行时；否定和肯定一般疑问，新谓语组合暂不提供自动纠错。", examples: [{ title: "进行 · 陈述", text: "She is sleeping." }, { title: "进行 · 疑问", text: "Were they giving her a book?" }] },
  { title: "简单句与限定纠错", scope: "五种句型、四种用途；支持一般现在/过去时和限定 can。纠错例句会显示形式不匹配。", examples: examples.slice(0, 19) },
  { title: "if 条件从句", scope: "仅前置 If + 条件从句, + 主句，必须有一个英文逗号。两侧完整陈述，不推断语义或时态搭配。", examples: examples.slice(19, 21) },
  { title: "because 原因从句", scope: "仅主句 + because + 原因从句，无逗号。两侧均有显式主语。", examples: examples.slice(21, 23) },
  { title: "and / but 并列句", scope: "仅两个完整陈述分句，连接词前可有一个逗号；共享主语和多重连接尚未支持。", examples: examples.slice(23, 26) },
  { title: "词典范围示例", scope: "此例含未覆盖词，会提示范围限制；这不表示句子存在语法错误。", examples: examples.slice(26) },
];
